import { readFileSync } from 'fs';

import { v6Parser } from './parser';
import { IPro6Arrangement, IPro6Properties, IPro6SlideGroup } from './parser.model';

describe('V6 - Parser', (): void => {
  let parser: v6Parser;

  beforeEach(() => {
    parser = new v6Parser();
  });

  it('should exist', () => {
    expect(parser).toBeDefined();
  });

  it('should throw an error for a ProPresenter file of a different version number', () => {
    try {
      const testFile = readFileSync('./sample-files/v4 - Be Near.pro4').toString();
      parser.parse(testFile);

      //Test should fail if no error is thrown
      expect(true).toBe(false);
    } catch (err: unknown) {
      expect(err).toEqual(Error(`Expected a ProPresenter 6 file with versionNumber="600" but got versionNumber="400"`));
    }
  });

  it('should get the data from "Amazing Grace.pro6', () => {
    const testFile = readFileSync('./sample-files/v6 - Amazing Grace.pro6').toString();
    const parsedSong = parser.parse(testFile);

    expect(parsedSong.properties).toEqual({
      CCLIArtistCredits: 'John Newton',
      CCLIAuthor: '',
      CCLICopyrightYear: '',
      CCLIDisplay: false,
      CCLIPublisher: '',
      CCLISongNumber: '',
      CCLISongTitle: 'Amazing Grace',
      backgroundColor: { r: 0, g: 0, b: 0 },
      buildNumber: 6016,
      category: 'Song',
      chordChartPath: '',
      docType: 0,
      drawingBackgroundColor: false,
      height: 1080,
      lastDateUsed: new Date('2023-06-16T02:27:25+00:00'),
      notes: '',
      os: 1,
      resourcesDirectory: '',
      selectedArrangementID: '',
      usedCount: 0,
      versionNumber: 600,
      width: 1920,
    } as IPro6Properties);

    expect(parsedSong.arrangements).toEqual([
      {
        color: { b: 255, g: 255, r: 255 },
        groupOrder: [
          { groupId: '5CB33287-B7EC-37BF-46E4-64DF8B619FD5', groupLabel: 'Blank' },
          { groupId: '1E80B87B-831A-A1D5-7D5F-0F42AE338C89', groupLabel: 'Verse 1' },
          { groupId: 'C7CE935F-2321-48C2-BBCA-5DEC88557BBF', groupLabel: 'Verse 2' },
          { groupId: 'C8430423-1BEC-4713-8589-F91DE89A2721', groupLabel: 'Verse 3' },
          { groupId: 'DC7B53AF-F36F-4119-BDFA-F9BC398CBB94', groupLabel: 'Verse 4' },
          { groupId: '5CB33287-B7EC-37BF-46E4-64DF8B619FD5', groupLabel: 'Blank' },
        ],
        label: 'Worship',
      },
    ] as IPro6Arrangement[]);

    expect(parsedSong.slideGroups).toEqual([
      {
        groupColor: { b: 0, g: 0, r: 255 },
        groupId: '5CB33287-B7EC-37BF-46E4-64DF8B619FD5',
        groupLabel: 'Blank',
        slides: [
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { b: 255, g: 255, r: 255 },
            hotKey: '',
            id: '6E8CD042-6592-87B4-9A33-61C025FD5D28',
            label: '',
            notes: '',
            textElements: [],
          },
        ],
      },
      {
        groupColor: { b: 255, g: 0, r: 0 },
        groupId: '1E80B87B-831A-A1D5-7D5F-0F42AE338C89',
        groupLabel: 'Verse 1',
        slides: [
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: null,
            hotKey: '',
            id: 'B2ADFDF1-C3F5-850E-8344-7E379BFE827A',
            label: '',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { b: 255, g: 255, r: 255 },
                fromTemplate: false,
                id: '9328c28d-fe52-4fe9-99be-49ce26f242db',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                plainText: 'Amazing grace how sweet the sound\r\nThat saved a wretch like me',
                fontName: 'Impact',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 74.5,
                position: { height: 1040, width: 1880, x: 20, y: 20, z: 0 },
                revealType: 0,
                rotation: 0,
                // cspell:disable-next-line
                rtfData: `{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Arial;}{\\f4\\fcharset0 Impact;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs120\\f3\\cf1 \\cf1\\qc{\\fs149\\f4 {\\cf2\\ltrch Amazing grace how sweet the sound}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n{\\fs149\\f4 {\\cf2\\ltrch That saved a wretch like me}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}`,
                textShadow: {
                  angle: 135,
                  color: { b: 0, g: 0, r: 0 },
                  enabled: false,
                  length: 7,
                  radius: 10,
                },
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                winFlowData:
                  '<FlowDocument TextAlignment="Center" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Arial" FontSize="60"><Run FontFamily="Impact" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center">Amazing grace how sweet the sound</Run></Paragraph><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Arial" FontSize="60"><Run FontFamily="Impact" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center">That saved a wretch like me</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: null,
            hotKey: '',
            id: 'B12B2C43-9D29-4DDC-98C3-EE95EB3B6A30',
            label: '',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { b: 255, g: 255, r: 255 },
                fromTemplate: false,
                id: '66b37b9a-4513-40df-8d81-12e8f756c43e',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                plainText: "I once was lost but now I'm found\r\nWas blind but now I see",
                fontName: 'Impact',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 74.5,
                position: { height: 1040, width: 1880, x: 20, y: 20, z: 0 },
                revealType: 0,
                rotation: 0,
                // cspell:disable-next-line
                rtfData: `{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Impact;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\f2\\cf1 \\cf1\\qc{\\fs149\\f3 {\\cf2\\ltrch I once was lost but now I'm found}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n{\\fs149\\f3 {\\cf2\\ltrch Was blind but now I see}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}`,
                textShadow: {
                  angle: 135,
                  color: { b: 0, g: 0, r: 0 },
                  enabled: false,
                  length: 7,
                  radius: 10,
                },
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                winFlowData:
                  '<FlowDocument FontFamily="Georgia" TextAlignment="Center" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Center"><Run FontFamily="Impact" FontStyle="Normal" FontWeight="Normal" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>I once was lost but now I\'m found</Run></Paragraph><Paragraph TextAlignment="Center"><Run FontFamily="Impact" FontStyle="Normal" FontWeight="Normal" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>Was blind but now I see</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              },
            ],
          },
        ],
      },
      {
        groupColor: { b: 127.00000000000013, g: 255, r: 0 },
        groupId: 'C7CE935F-2321-48C2-BBCA-5DEC88557BBF',
        groupLabel: 'Verse 2',
        slides: [
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: null,
            hotKey: '',
            id: 'C76B1CF4-9B09-F06C-C08C-FE6C60A2EE53',
            label: '',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { b: 255, g: 255, r: 255 },
                fromTemplate: false,
                id: '1fd699c8-b784-46b6-8d80-672d665f852e',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                plainText: 'Twas grace that taught my heart to fear\r\nAnd grace my fears relieved',
                fontName: 'Impact',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 74.5,
                position: { height: 1040, width: 1880, x: 20, y: 20, z: 0 },
                revealType: 0,
                rotation: 0,
                // cspell:disable-next-line
                rtfData: `{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Arial;}{\\f4\\fcharset0 Impact;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs120\\f3\\cf1 \\cf1\\qc{\\fs149\\f4 {\\cf2\\ltrch Twas grace that taught my heart to fear}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n{\\fs149\\f4 {\\cf2\\ltrch And grace my fears relieved}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}`,
                textShadow: {
                  angle: 135,
                  color: { b: 0, g: 0, r: 0 },
                  enabled: false,
                  length: 7,
                  radius: 10,
                },
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                winFlowData:
                  '<FlowDocument TextAlignment="Center" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Arial" FontSize="60"><Run FontFamily="Impact" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center">Twas grace that taught my heart to fear</Run></Paragraph><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Arial" FontSize="60"><Run FontFamily="Impact" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center">And grace my fears relieved</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: null,
            hotKey: '',
            id: '6575EB64-68BB-4294-B048-678DD825AA0F',
            label: '',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { b: 255, g: 255, r: 255 },
                fromTemplate: false,
                id: '611d85cd-15d9-4f81-b214-15e120ccb75d',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                plainText: 'How precious did that grace appear\r\nThe hour I first believed',
                fontName: 'Impact',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 74.5,
                position: { height: 1040, width: 1880, x: 20, y: 20, z: 0 },
                revealType: 0,
                rotation: 0,
                // cspell:disable-next-line
                rtfData: `{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Impact;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\f2\\cf1 \\cf1\\qc{\\fs149\\f3 {\\cf2\\ltrch How precious did that grace appear}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n{\\fs149\\f3 {\\cf2\\ltrch The hour I first believed}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}`,
                textShadow: {
                  angle: 135,
                  color: { b: 0, g: 0, r: 0 },
                  enabled: false,
                  length: 7,
                  radius: 10,
                },
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                winFlowData:
                  '<FlowDocument FontFamily="Georgia" TextAlignment="Center" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Center"><Run FontFamily="Impact" FontStyle="Normal" FontWeight="Normal" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>How precious did that grace appear</Run></Paragraph><Paragraph TextAlignment="Center"><Run FontFamily="Impact" FontStyle="Normal" FontWeight="Normal" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>The hour I first believed</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              },
            ],
          },
        ],
      },
      {
        groupColor: { b: 0, g: 165.00000000000006, r: 255 },
        groupId: 'C8430423-1BEC-4713-8589-F91DE89A2721',
        groupLabel: 'Verse 3',
        slides: [
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: null,
            hotKey: '',
            id: 'F263B3B9-717A-AC3B-E150-5B95125B6E45',
            label: '',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { b: 255, g: 255, r: 255 },
                fromTemplate: false,
                id: '58b00854-cb27-445f-99cc-1b5c1a5a21e8',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                plainText: 'Through many dangers, toils\r\nAnd snares I have already come',
                fontName: 'Impact',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 74.5,
                position: { height: 1040, width: 1880, x: 20, y: 20, z: 0 },
                revealType: 0,
                rotation: 0,
                // cspell:disable-next-line
                rtfData: `{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Arial;}{\\f4\\fcharset0 Impact;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs120\\f3\\cf1 \\cf1\\qc{\\fs149\\f4 {\\cf2\\ltrch Through many dangers, toils}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n{\\fs149\\f4 {\\cf2\\ltrch And snares I have already come}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}`,
                textShadow: {
                  angle: 135,
                  color: { b: 0, g: 0, r: 0 },
                  enabled: false,
                  length: 7,
                  radius: 10,
                },
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                winFlowData:
                  '<FlowDocument TextAlignment="Center" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Arial" FontSize="60"><Run FontFamily="Impact" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center">Through many dangers, toils</Run></Paragraph><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Arial" FontSize="60"><Run FontFamily="Impact" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center">And snares I have already come</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: null,
            hotKey: '',
            id: 'B61CB10A-AB7C-465F-B7DA-816DBA2B9094',
            label: '',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { b: 255, g: 255, r: 255 },
                fromTemplate: false,
                id: '81f5e9ab-2ca5-4c39-b857-e9992aa165cd',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                plainText: "'Tis grace that brought me safe thus far\r\nAnd grace will lead me home",
                fontName: 'Impact',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 74.5,
                position: { height: 1040, width: 1880, x: 20, y: 20, z: 0 },
                revealType: 0,
                rotation: 0,
                // cspell:disable-next-line
                rtfData: `{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Impact;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\f2\\cf1 \\cf1\\qc{\\fs149\\f3 {\\cf2\\ltrch 'Tis grace that brought me safe thus far}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n{\\fs149\\f3 {\\cf2\\ltrch And grace will lead me home}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}`,
                textShadow: {
                  angle: 135,
                  color: { b: 0, g: 0, r: 0 },
                  enabled: false,
                  length: 7,
                  radius: 10,
                },
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                winFlowData:
                  '<FlowDocument FontFamily="Georgia" TextAlignment="Center" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Center"><Run FontFamily="Impact" FontStyle="Normal" FontWeight="Normal" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>\'Tis grace that brought me safe thus far</Run></Paragraph><Paragraph TextAlignment="Center"><Run FontFamily="Impact" FontStyle="Normal" FontWeight="Normal" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>And grace will lead me home</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              },
            ],
          },
        ],
      },
      {
        groupColor: { b: 255, g: 255, r: 0 },
        groupId: 'DC7B53AF-F36F-4119-BDFA-F9BC398CBB94',
        groupLabel: 'Verse 4',
        slides: [
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: null,
            hotKey: '',
            id: 'BCA1870E-3354-D0A0-275E-374EAC53A2EC',
            label: '',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { b: 255, g: 255, r: 255 },
                fromTemplate: false,
                id: '67cde87b-6c32-42a8-93b4-fd17094d46d7',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                plainText: "When we've been there ten thousand years\r\nBright shining as the sun",
                fontName: 'Impact',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 74.5,
                position: { height: 1040, width: 1880, x: 20, y: 20, z: 0 },
                revealType: 0,
                rotation: 0,
                // cspell:disable-next-line
                rtfData: `{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Arial;}{\\f4\\fcharset0 Impact;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs120\\f3\\cf1 \\cf1\\qc{\\fs149\\f4 {\\cf2\\ltrch When we've been there ten thousand years}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n{\\fs149\\f4 {\\cf2\\ltrch Bright shining as the sun}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}`,
                textShadow: {
                  angle: 135,
                  color: { b: 0, g: 0, r: 0 },
                  enabled: false,
                  length: 7,
                  radius: 10,
                },
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                winFlowData:
                  '<FlowDocument TextAlignment="Center" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Arial" FontSize="60"><Run FontFamily="Impact" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center">When we\'ve been there ten thousand years</Run></Paragraph><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Arial" FontSize="60"><Run FontFamily="Impact" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center">Bright shining as the sun</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: null,
            hotKey: '',
            id: '0F4D13B3-BE99-4744-8270-BCD624734A8B',
            label: '',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { b: 255, g: 255, r: 255 },
                fromTemplate: false,
                id: '69bddec1-032a-4123-97d8-23bcd1a75ca5',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                plainText: "We've no less days to sing God's praise\r\nThan when we'd first begun!",
                fontName: 'Impact',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 74.5,
                position: { height: 1040, width: 1880, x: 20, y: 20, z: 0 },
                revealType: 0,
                rotation: 0,
                // cspell:disable-next-line
                rtfData: `{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Impact;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\f2\\cf1 \\cf1\\qc{\\fs149\\f3 {\\cf2\\ltrch We've no less days to sing God's praise}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n{\\fs149\\f3 {\\cf2\\ltrch Than when we'd first begun!}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}`,
                textShadow: {
                  angle: 135,
                  color: { b: 0, g: 0, r: 0 },
                  enabled: false,
                  length: 7,
                  radius: 10,
                },
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                winFlowData:
                  '<FlowDocument FontFamily="Georgia" TextAlignment="Center" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Center"><Run FontFamily="Impact" FontStyle="Normal" FontWeight="Normal" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>We\'ve no less days to sing God\'s praise</Run></Paragraph><Paragraph TextAlignment="Center"><Run FontFamily="Impact" FontStyle="Normal" FontWeight="Normal" FontStretch="Condensed" FontSize="75" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>Than when we\'d first begun!</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              },
            ],
          },
        ],
      },
    ] as IPro6SlideGroup[]);
  });

  it('should get the data from "Be Near.pro6', () => {
    const testFile = readFileSync('./sample-files/v6 - Be Near.pro6').toString();
    const parsedSong = parser.parse(testFile);

    expect(parsedSong.properties).toEqual({
      CCLIArtistCredits: 'Shane Bernard',
      CCLIAuthor: '',
      CCLICopyrightYear: 2003,
      CCLIDisplay: false,
      CCLIPublisher: 'Waiting Room Music',
      CCLISongNumber: '',
      CCLISongTitle: 'Be Near',
      backgroundColor: { r: 0, g: 0, b: 0 },
      buildNumber: 6016,
      category: 'Song',
      chordChartPath: '',
      docType: 0,
      drawingBackgroundColor: false,
      height: 1080,
      lastDateUsed: new Date('2023-05-18T00:03:20+00:00'),
      notes: '',
      os: 1,
      resourcesDirectory: '',
      selectedArrangementID: '',
      usedCount: 0,
      versionNumber: 600,
      width: 1920,
    } as IPro6Properties);

    expect(parsedSong.arrangements).toEqual([] as IPro6Arrangement[]);

    expect(parsedSong.slideGroups).toEqual([
      {
        groupColor: { r: 255, g: 0, b: 0 },
        groupId: '48EACA8B-2730-B0C2-C0F5-776AA778134E',
        groupLabel: 'Blank',
        slides: [
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 255, g: 255, b: 255 },
            hotKey: '',
            id: '860C8AC7-CD8C-8319-711D-C6095E7C0BA1',
            label: '',
            notes: '',
            textElements: [],
          },
        ],
      },
      {
        groupColor: { r: 0, g: 0, b: 255 },
        groupId: '0C5F27FA-9BAC-35E6-6430-D12B7E662676',
        groupLabel: 'Song',
        slides: [
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: 'A737E69B-461B-E755-5C30-DEA9326EAE6F',
            label: 'Background',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: '2fe72400-fa4b-49d8-aa8b-dd8af66c26be',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: '7C5A6BFF-AE87-8FB1-A156-277D5250BEE6',
            label: 'Verse 1 (1)',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: '1982d02b-be6a-41e7-b7a4-67bf5a077790',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',\r\nYou are all\r\nBig and small\r\nBeautiful",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Arial;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\loch\\f3\\fs120\\ltrch ',}{\\cf2\\ltrch {\\loch\\f3\\fs120 }\\line }{\\loch\\f3\\fs120\\cf2\\ltrch You are all}{\\cf2\\ltrch {\\loch\\f3\\fs120 }\\line }{\\loch\\f3\\fs120\\cf2\\ltrch Big and small}{\\cf2\\ltrch {\\loch\\f3\\fs120 }\\line }{\\loch\\f3\\fs120\\cf2\\ltrch Beautiful}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Run FontFamily="Arial" FontSize="60" Block.TextAlignment="Center">\',</Run><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><Run FontFamily="Arial" FontSize="60" Block.TextAlignment="Center" xml:space="preserve" /><LineBreak Block.TextAlignment="Center" /></Span><Run FontFamily="Arial" FontSize="60" Foreground="#FFFFFFFF" Block.TextAlignment="Center">You are all</Run><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><Run FontFamily="Arial" FontSize="60" Block.TextAlignment="Center" xml:space="preserve" /><LineBreak Block.TextAlignment="Center" /></Span><Run FontFamily="Arial" FontSize="60" Foreground="#FFFFFFFF" Block.TextAlignment="Center">Big and small</Run><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><Run FontFamily="Arial" FontSize="60" Block.TextAlignment="Center" xml:space="preserve" /><LineBreak Block.TextAlignment="Center" /></Span><Run FontFamily="Arial" FontSize="60" Foreground="#FFFFFFFF" Block.TextAlignment="Center">Beautiful</Run></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Arial',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 60,
                position: { x: 20, y: 20, z: 0, width: 1876, height: 1012 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: 'CAC000A3-6ED1-C8F0-3845-77807F429FB7',
            label: 'Verse 1 (2)',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: '6fe9f003-01de-4be6-a2bd-e4efa1555c91',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',\r\nAnd wonderful to \r\nTrust in grace\r\nThrough faith\r\nBut I'm asking to taste",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }{\\cf2\\ltrch And wonderful to }{\\cf2\\ltrch \\line }{\\cf2\\ltrch Trust in grace}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Through faith}{\\cf2\\ltrch \\line }{\\cf2\\ltrch But I'm asking to taste}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center" xml:space="preserve">And wonderful to </Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Trust in grace</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Through faith</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">But I\'m asking to taste</Run></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: '21030921-B9F0-EC85-5101-327B24445DBD',
            label: 'Bridge 1',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: 'b70ac068-43c7-48a2-8e16-c37567665d18',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText:
                  "',\r\nFor dark is light to You\r\nDepths are Height to you\r\nFar is near\r\nBut Lord I need to hear from You",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }{\\cf2\\ltrch For dark is light to You}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Depths are Height to you}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Far is near}{\\cf2\\ltrch \\line }{\\cf2\\ltrch But Lord I need to hear from You}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">For dark is light to You</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Depths are Height to you</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Far is near</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">But Lord I need to hear from You</Run></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: '45D804B7-A72A-5189-1EE2-66C8C51E34AD',
            label: 'Chorus',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: 'fbf4e69f-856a-4993-a9b6-667ba19ab1c0',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',\r\nBe near O God\r\nBe near O God of us\r\nYour nearness is\r\nTo us our good",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Be near O God}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Be near O God of us}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Your nearness is}{\\cf2\\ltrch \\line }{\\cf2\\ltrch To us our good}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Be near O God</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Be near O God of us</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Your nearness is</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">To us our good</Run></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: '323DAC19-00FE-E656-C1BC-66C171199624',
            label: 'Post-Chorus',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: '85b6fd08-fe4b-4083-8c36-161858d32437',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',\r\nOur Good",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Our Good}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Our Good</Run></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: 'BA04580C-265F-8495-932A-D7A3FB576C78',
            label: 'Verse 2 (1)',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: '1b638cee-b05e-41e3-a0be-ebc87fea1f7c',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',\r\nYour fullness is mine\r\nRevelation Divine",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Your fullness is mine}{\\cf2\\ltrch \\line }{\\cf2\\ltrch Revelation Divine}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Your fullness is mine</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">Revelation Divine</Run></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: 'EAE6FA3B-5051-79CB-3058-DBC8486FE31F',
            label: 'Verse 2 (2)',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: '726feb95-0a25-4109-a19e-744e2e68076f',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',\r\nBut oh to taste\r\nTo know much\r\nMore than a page\r\nTo feel Your embrace",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }{\\cf2\\ltrch But oh to taste}{\\cf2\\ltrch \\line }{\\cf2\\ltrch To know much}{\\cf2\\ltrch \\line }{\\cf2\\ltrch More than a page}{\\cf2\\ltrch \\line }{\\cf2\\ltrch To feel Your embrace}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">But oh to taste</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">To know much</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">More than a page</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">To feel Your embrace</Run></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: '3E58D13C-BD77-BD60-728E-C19877FD2A4A',
            label: 'Ending',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: '259a0abe-4a3b-4c80-ae63-40f9d96f8fe8',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',\r\nMy Good",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }{\\cf2\\ltrch My Good}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span><Span Foreground="#FFFFFFFF"><Run Block.TextAlignment="Center">My Good</Run></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 0, g: 0, b: 0 },
            hotKey: '',
            id: 'AEBD3A3D-1B73-F89E-47EE-00D97FBF4AA6',
            label: '*blank*',
            notes: '',
            textElements: [
              {
                adjustsHeightToFit: false,
                bezelRadius: 0,
                displayDelay: 0,
                displayName: 'Default',
                drawingFill: false,
                fillColor: { r: 255, g: 255, b: 255 },
                fromTemplate: false,
                id: '71d8f6b3-2dfc-41cf-984d-a2546ea17d09',
                locked: false,
                opacity: 1,
                outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
                persistent: 0,
                revealType: 0,
                rotation: 0,
                source: '',
                typeID: 0,
                verticalAlignment: 0,
                plainText: "',",
                rtfData:
                  // cspell:disable-next-line
                  "{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs96\\f0\\cf1 \\cf1\\ql{\\f0 {\\fs32\\ltrch ',}{\\cf2\\ltrch \\line }\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}",
                winFlowData:
                  '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph Margin="0,0,0,0" TextAlignment="Center" FontFamily="Times New Roman" FontSize="48"><Span FontSize="16"><Run Block.TextAlignment="Center">\',</Run></Span><Span FontFamily="Times New Roman" FontSize="48" Foreground="#FFFFFFFF"><LineBreak Block.TextAlignment="Center" /></Span></Paragraph></FlowDocument>',
                winFontData:
                  '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
                fontName: 'Georgia',
                textColor: { r: 255, g: 255, b: 255 },
                textSize: 16,
                position: { x: 20, y: 20, z: 0, width: 984, height: 728 },
                textShadow: {
                  angle: 135,
                  color: { r: 0, g: 0, b: 0 },
                  enabled: false,
                  length: 5,
                  radius: 5,
                },
              },
            ],
          },
        ],
      },
      {
        groupColor: { r: 255, g: 0, b: 0 },
        groupId: '4EE6777E-FC6A-9CC1-4B31-C007EC8B2BDA',
        groupLabel: 'Blank',
        slides: [
          {
            backgroundColor: { r: 0, g: 0, b: 0 },
            chordChartPath: '',
            drawingBackgroundColor: false,
            enabled: true,
            highlightColor: { r: 255, g: 255, b: 255 },
            hotKey: '',
            id: '40A96A7F-986B-9E09-C081-30DEDFDB41D9',
            label: '',
            notes: '',
            textElements: [],
          },
        ],
      },
    ] as IPro6SlideGroup[]);
  });

  it('should get the data from "Feature Test.pro6', () => {
    const testFile = readFileSync('./sample-files/v6 - Feature Test.pro6').toString();
    const parsedSong = parser.parse(testFile);

    expect(parsedSong.properties).toEqual({
      CCLIArtistCredits: '',
      CCLIAuthor: '',
      CCLICopyrightYear: '',
      CCLIDisplay: false,
      CCLIPublisher: '',
      CCLISongNumber: '',
      CCLISongTitle: '',
      backgroundColor: { r: 49.99999999999999, g: 164.00000000000006, b: 156 },
      buildNumber: 6016,
      category: 'Song',
      chordChartPath: '',
      docType: 0,
      drawingBackgroundColor: true,
      height: 1080,
      lastDateUsed: new Date('2023-06-19T19:11:43+00:00'),
      notes: '',
      os: 1,
      resourcesDirectory: '',
      selectedArrangementID: '',
      usedCount: 0,
      versionNumber: 600,
      width: 1920,
    } as IPro6Properties);

    expect(parsedSong.arrangements).toEqual([] as IPro6Arrangement[]);

    expect(parsedSong.slideGroups.length).toEqual(3);

    expect(parsedSong.slideGroups[0]).toEqual({
      groupColor: { b: 0, g: 0, r: 0 },
      groupId: '146F03EB-5E64-62CF-A511-AB1E38EE8A44',
      groupLabel: 'Blank',
      slides: [
        {
          backgroundColor: { b: 0, g: 0, r: 0 },
          chordChartPath: '',
          drawingBackgroundColor: false,
          enabled: true,
          highlightColor: { b: 0, g: 0, r: 0 },
          hotKey: '',
          id: 'C8F69785-1146-1020-B79B-2B3FB564B20E',
          label: '',
          notes: '',
          textElements: [],
        },
      ],
    });

    expect(parsedSong.slideGroups[1]).toEqual({
      groupColor: { r: 255, g: 255, b: 255 },
      groupId: 'ACFD5281-A303-4E73-8B54-63BEAB7D85C9',
      groupLabel: '',
      slides: [
        {
          backgroundColor: {
            r: 65.00000000000007,
            g: 74.00000000000011,
            b: 135.99999999999991,
          },
          chordChartPath: '',
          drawingBackgroundColor: true,
          enabled: true,
          highlightColor: { r: 0, g: 255, b: 127.00000000000013 },
          hotKey: 'G',
          id: 'F92126F4-1AEC-435F-BB14-E3864254643E',
          label: 'Spoken Word',
          notes: '',
          textElements: [
            {
              adjustsHeightToFit: false,
              bezelRadius: 40,
              displayDelay: 0,
              displayName: '2nd box',
              drawingFill: true,
              fillColor: {
                r: 180.0000000000001,
                g: 23.999999999999993,
                b: 23.999999999999993,
              },
              fromTemplate: false,
              id: 'fd5344fd-dec1-4dd0-afb8-2f1f5985e332',
              locked: false,
              opacity: 1,
              outline: { color: { r: 16.000000000000004, g: 239.99999999999991, b: 70.00000000000009 }, enabled: true, size: 12 },
              persistent: 0,
              revealType: 1,
              rotation: 346,
              source: '',
              typeID: 0,
              verticalAlignment: 0,
              fontName: 'Helvetica',
              textColor: { r: 151, g: 238, b: 21 },
              textSize: 70.5,
              plainText: 'two',
              rtfData:
                // cspell:disable-next-line
                '{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Helvetica;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;\\red151\\green238\\blue21;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\outl0\\strokewidth-100\\strokec3\\f2\\cf1 \\cf1\\ql{\\fs141\\outl0\\strokewidth-100\\strokec3\\f3 {\\cf2\\ltrch two}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}',
              winFlowData:
                '<FlowDocument TextAlignment="Left" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Center"><Run FontFamily="Helvetica" FontStyle="Normal" FontWeight="Normal" FontStretch="Normal" FontSize="71" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>two</Run></Paragraph></FlowDocument>',
              winFontData:
                '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>21</d2p1:B><d2p1:G>238</d2p1:G><d2p1:R>151</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0.007499032</d2p1:ScB><d2p1:ScG>0.8549926</d2p1:ScG><d2p1:ScR>0.309468925</d2p1:ScR></OutlineColor><OutlineWidth>5</OutlineWidth><Variants>Normal</Variants></RVFont>',
              position: { x: 117, y: 520, z: 0, width: 900, height: 399 },
              textShadow: {
                angle: 154.99999999999997,
                color: { r: 0, g: 0, b: 0 },
                enabled: true,
                length: 10,
                radius: 10,
              },
            },
            {
              adjustsHeightToFit: false,
              bezelRadius: 40,
              displayDelay: 0,
              displayName: 'first box',
              drawingFill: true,
              fillColor: {
                r: 180.0000000000001,
                g: 25.999999999999876,
                b: 25.999999999999876,
              },
              fromTemplate: false,
              id: '75a4195f-ecb7-40e8-ac18-6ded0f4bdb92',
              locked: true,
              opacity: 1,
              outline: { color: { r: 16.000000000000004, g: 241.99999999999994, b: 70.00000000000009 }, enabled: true, size: 12 },
              persistent: 0,
              revealType: 1,
              rotation: 6,
              source: '',
              typeID: 0,
              verticalAlignment: 0,
              fontName: 'Helvetica',
              textColor: { r: 255, g: 255, b: 255 },
              textSize: 100,
              plainText: 'one',
              rtfData:
                // cspell:disable-next-line
                '{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Helvetica;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\outl0\\strokewidth-200\\strokec1\\f2\\cf1 \\cf1\\ql{\\fs200\\outl0\\strokewidth-200\\strokec1\\f3 {\\cf2\\ltrch one}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}',
              winFlowData:
                '<FlowDocument TextAlignment="Left" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Center"><Run FontFamily="Helvetica" FontStyle="Normal" FontWeight="Normal" FontStretch="Normal" FontSize="100" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>one</Run></Paragraph></FlowDocument>',
              winFontData:
                '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>10</OutlineWidth><Variants>Normal</Variants></RVFont>',
              position: { x: 948, y: 126, z: 0, width: 900, height: 399 },
              textShadow: {
                angle: 135,
                color: { r: 0, g: 0, b: 0 },
                enabled: false,
                length: 4,
                radius: 4,
              },
            },
          ],
        },
        {
          backgroundColor: { r: 0, g: 0, b: 0 },
          chordChartPath: '',
          drawingBackgroundColor: false,
          enabled: true,
          highlightColor: null,
          hotKey: '',
          id: '89ED8DAD-307B-4ECE-83B5-410A54A67E36',
          label: '',
          notes: '',
          textElements: [
            {
              adjustsHeightToFit: false,
              bezelRadius: 0,
              displayDelay: 0,
              displayName: 'Bible Text',
              drawingFill: false,
              fillColor: { r: 0, g: 0, b: 0 },
              fromTemplate: false,
              id: 'ac989cfb-baa2-4df0-9f54-ac04759a3fe4',
              locked: false,
              opacity: 1,
              outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
              persistent: 0,
              revealType: 0,
              rotation: 0,
              source: '',
              typeID: 0,
              verticalAlignment: 0,
              fontName: 'Georgia',
              textColor: { r: 255, g: 255, b: 255 },
              textSize: 46.5,
              plainText: 'Lower 3rd text',
              rtfData:
                // cspell:disable-next-line
                '{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\f2\\cf1 \\cf1\\ql{\\fs93\\f2 {\\i\\cf2\\ltrch Lower 3rd text}\\li0\\sa0\\sb0\\fi0\\ql}\r\n}\r\n}',
              winFlowData:
                '<FlowDocument TextAlignment="Left" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Left"><Run FontFamily="Georgia" FontStyle="Italic" FontWeight="Normal" FontStretch="Normal" FontSize="46.6666666666667" Foreground="#FFFFFFFF" Block.TextAlignment="Left"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>Lower 3rd text</Run></Paragraph></FlowDocument>',
              winFontData:
                '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              position: { x: 105, y: 757, z: 0, width: 1685, height: 167 },
              textShadow: {
                angle: 135,
                color: { r: 0, g: 0, b: 0 },
                enabled: false,
                length: 6,
                radius: 0,
              },
            },
            {
              adjustsHeightToFit: false,
              bezelRadius: 0,
              displayDelay: 0,
              displayName: 'Bible Reference',
              drawingFill: false,
              fillColor: { r: 0, g: 0, b: 0 },
              fromTemplate: false,
              id: '2f94058a-4810-48a3-9149-8d47f89244d6',
              locked: false,
              opacity: 1,
              outline: { color: { r: 0, g: 0, b: 0 }, enabled: false, size: 0 },
              persistent: 0,
              revealType: 0,
              rotation: 0,
              source: '',
              typeID: 0,
              verticalAlignment: 0,
              fontName: 'Georgia',
              textColor: { r: 255, g: 255, b: 255 },
              textSize: 34.5,
              plainText: 'Other text in lower 3rd',
              rtfData:
                // cspell:disable-next-line
                '{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\f2\\cf1 \\cf1\\ql{\\fs69\\f2 {\\cf2\\ltrch Other text in lower 3rd}\\li0\\sa0\\sb0\\fi0\\qr\\par}\r\n}\r\n}',
              winFlowData:
                '<FlowDocument TextAlignment="Left" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Right"><Run FontFamily="Georgia" FontStyle="Normal" FontWeight="Normal" FontStretch="Normal" FontSize="34.6666666666667" Foreground="#FFFFFFFF" Block.TextAlignment="Right"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>Other text in lower 3rd</Run></Paragraph></FlowDocument>',
              winFontData:
                '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>0</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>0</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>0</OutlineWidth><Variants>Normal</Variants></RVFont>',
              position: { x: 928, y: 936, z: 0, width: 825, height: 55 },
              textShadow: {
                angle: 135,
                color: { r: 0, g: 0, b: 0 },
                enabled: false,
                length: 6,
                radius: 0,
              },
            },
          ],
        },
        {
          backgroundColor: { r: 0, g: 0, b: 0 },
          chordChartPath: '',
          drawingBackgroundColor: false,
          enabled: true,
          highlightColor: null,
          hotKey: '',
          id: '6077F608-7C14-4422-93AF-5ED2CA992D5C',
          label: '',
          notes: '',
          textElements: [
            {
              adjustsHeightToFit: false,
              bezelRadius: 0,
              displayDelay: 0,
              displayName: 'Default',
              drawingFill: false,
              fillColor: { r: 255, g: 255, b: 255 },
              fromTemplate: false,
              id: 'ec30b57c-203d-44ba-956e-3401bb2f4347',
              locked: false,
              opacity: 1,
              outline: { color: { r: 255, g: 255, b: 255 }, enabled: false, size: 0 },
              persistent: 0,
              revealType: 0,
              rotation: 0,
              source: '',
              typeID: 0,
              verticalAlignment: 0,
              fontName: 'Helvetica',
              textColor: { r: 255, g: 255, b: 255 },
              textSize: 71.5,
              plainText: 'Double-click to edit',
              rtfData:
                // cspell:disable-next-line
                '{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Helvetica;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\outl0\\strokewidth-20\\strokec1\\f2\\cf1 \\cf1\\ql{\\fs143\\outl0\\strokewidth-20\\strokec1\\f3 {\\cf2\\ltrch Double-click to edit}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}',
              winFlowData:
                '<FlowDocument TextAlignment="Left" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Center"><Run FontFamily="Helvetica" FontStyle="Normal" FontWeight="Normal" FontStretch="Normal" FontSize="71.25" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>Double-click to edit</Run></Paragraph></FlowDocument>',
              winFontData:
                '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>1</OutlineWidth><Variants>Normal</Variants></RVFont>',
              position: { x: 56, y: 42, z: 0, width: 1808, height: 996 },
              textShadow: {
                angle: 135,
                color: { r: 0, g: 0, b: 0 },
                enabled: false,
                length: 4,
                radius: 4,
              },
            },
          ],
        },
      ],
    } as IPro6SlideGroup);

    expect(parsedSong.slideGroups[2]).toEqual({
      groupColor: { r: 0, g: 0, b: 0 },
      groupId: 'A5DD037E-58A4-4629-984D-8186A43AC684',
      groupLabel: 'Tag',
      slides: [
        {
          backgroundColor: { r: 0, g: 0, b: 0 },
          chordChartPath: '',
          drawingBackgroundColor: false,
          enabled: true,
          highlightColor: null,
          hotKey: '',
          id: 'DB551011-32E0-4A2F-9EE5-0E29F72D72D9',
          label: '',
          notes: '',
          textElements: [
            {
              adjustsHeightToFit: false,
              bezelRadius: 0,
              displayDelay: 0,
              displayName: 'Default',
              drawingFill: false,
              fillColor: { r: 255, g: 255, b: 255 },
              fromTemplate: false,
              id: '9b186dda-86c3-4448-b076-8edb1b7e24bf',
              locked: false,
              opacity: 1,
              outline: { color: { r: 255, g: 255, b: 255 }, enabled: false, size: 0 },
              persistent: 0,
              revealType: 0,
              rotation: 0,
              source: '',
              typeID: 0,
              verticalAlignment: 0,
              fontName: 'Helvetica',
              textColor: { r: 255, g: 255, b: 255 },
              textSize: 70.5,
              plainText: 'Double-click to edit',
              rtfData:
                // cspell:disable-next-line
                '{\\rtf1\\prortf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 Georgia;}{\\f3\\fcharset0 Helvetica;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\slleading0\\plain\\ltrpar\\itap0{\\lang1033\\fs32\\outl0\\strokewidth-20\\strokec1\\f2\\cf1 \\cf1\\ql{\\fs141\\outl0\\strokewidth-20\\strokec1\\f3 {\\cf2\\ltrch Double-click to edit}\\li0\\sa0\\sb0\\fi0\\qc\\par}\r\n}\r\n}',
              winFlowData:
                '<FlowDocument TextAlignment="Left" PagePadding="5,0,5,0" AllowDrop="True" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Paragraph TextAlignment="Center"><Run FontFamily="Helvetica" FontStyle="Normal" FontWeight="Normal" FontStretch="Normal" FontSize="71" Foreground="#FFFFFFFF" Block.TextAlignment="Center"><Run.TextDecorations><TextDecorationCollection /></Run.TextDecorations>Double-click to edit</Run></Paragraph></FlowDocument>',
              winFontData:
                '<?xml version="1.0" encoding="utf-16"?><RVFont xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ProPresenter.Common"><Kerning>0</Kerning><LineSpacing>0</LineSpacing><OutlineColor xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Windows.Media"><d2p1:A>255</d2p1:A><d2p1:B>0</d2p1:B><d2p1:G>0</d2p1:G><d2p1:R>0</d2p1:R><d2p1:ScA>1</d2p1:ScA><d2p1:ScB>0</d2p1:ScB><d2p1:ScG>0</d2p1:ScG><d2p1:ScR>0</d2p1:ScR></OutlineColor><OutlineWidth>1</OutlineWidth><Variants>Normal</Variants></RVFont>',
              position: { x: 56, y: 42, z: 0, width: 1808, height: 996 },
              textShadow: {
                angle: 135,
                color: { r: 0, g: 0, b: 0 },
                enabled: false,
                length: 4,
                radius: 4,
              },
            },
          ],
        },
      ],
    } as IPro6SlideGroup);
  });
});
